version: '3'

services:
  mywebsite:
    build:
      context: .
    ports:
      - "80:8000"
    volumes:
      - ./mywebsite:/mywebsite
    command: >
          sh -c "python manage.py runserver 0.0.0.0:8000"
